export const Languages = [
  { key: 1, value: 'Mandarin Chinese' },
  { key: 2, value: 'Spanish' },
  { key: 3, value: 'English' },
  { key: 4, value: 'Hindi' },
  { key: 5, value: 'Bengali' },
  { key: 6, value: 'Portuguese' },
  { key: 7, value: 'Russian' },
  { key: 8, value: 'Japanese' },
  { key: 9, value: 'Western Punjabi' },
  { key: 10, value: 'Marathi' },
  { key: 11, value: 'Telugu' },
  { key: 12, value: 'Wu Chinese' },
  { key: 13, value: 'Turkish' },
  { key: 14, value: 'Korean' },
  { key: 15, value: 'French' },
  { key: 16, value: 'German' },
  { key: 17, value: 'Vietnamese' },
  { key: 18, value: 'Tamil' },
  { key: 19, value: 'Yue Chinese' },
  { key: 20, value: 'Urdu' },
  { key: 21, value: 'Javanese' },
  { key: 22, value: 'Italian' },
  { key: 23, value: 'Egyptian Arabic' },
  { key: 24, value: 'Gujarati' },
  { key: 25, value: 'Iranian Persian' },
  { key: 26, value: 'Bhojpuri' },
  { key: 27, value: 'Min Nan Chinese' },
  { key: 28, value: 'Hakka Chinese' },
  { key: 29, value: 'Jin Chinese' },
  { key: 30, value: 'Hausa' },
  { key: 31, value: 'Kannada' },
  { key: 32, value: 'Indonesian' },
  { key: 33, value: 'Polish' },
  { key: 34, value: 'Yoruba' },
  { key: 35, value: 'Xiang Chinese' },
  { key: 36, value: 'Malayalam' },
  { key: 37, value: 'Odia' },
  { key: 38, value: 'Maithili' },
  { key: 39, value: 'Burmese' },
  { key: 40, value: 'Eastern Punjabi' },
  { key: 41, value: 'Sunda' },
  { key: 42, value: 'Sudanese Arabic' },
  { key: 43, value: 'Algerian Arabic' },
  { key: 44, value: 'Moroccan Arabic' },
  { key: 45, value: 'Ukrainian' },
  { key: 46, value: 'Igbo' },
  { key: 47, value: 'Northern Uzbek' },
  { key: 48, value: 'Sindhi' },
  { key: 49, value: 'North Levantine Arabic' },
  { key: 50, value: 'Romanian' },
  { key: 51, value: 'Tagalog' },
  { key: 52, value: 'Dutch' },
  { key: 53, value: 'Saʽidi Arabic' },
  { key: 54, value: 'Gan Chinese' },
  { key: 55, value: 'Amharic' },
  { key: 56, value: 'Northern Pashto' },
  { key: 57, value: 'Magahi' },
  { key: 58, value: 'Thai' },
  { key: 59, value: 'Saraiki' },
  { key: 60, value: 'Khmer' },
  { key: 61, value: 'Chhattisgarhi' },
  { key: 62, value: 'Somali' },
  { key: 63, value: 'Malay (Malaysian Malay)' },
  { key: 64, value: 'Cebuano' },
  { key: 65, value: 'Nepali' },
  { key: 66, value: 'Mesopotamian Arabic' },
  { key: 67, value: 'Assamese' },
  { key: 68, value: 'Sinhalese' },
  { key: 69, value: 'Northern Kurdish' },
  { key: 70, value: 'Hejazi Arabic' },
  { key: 71, value: 'Nigerian Fulfulde' },
  { key: 72, value: 'Bavarian' },
  { key: 73, value: 'South Azerbaijani' },
  { key: 74, value: 'Greek' },
  { key: 75, value: 'Chittagonian' },
  { key: 76, value: 'Kazakh' },
  { key: 77, value: 'Deccan' },
  { key: 78, value: 'Hungarian' },
  { key: 79, value: 'Kinyarwanda' },
  { key: 80, value: 'Zulu' },
  { key: 81, value: 'South Levantine Arabic' },
  { key: 82, value: 'Tunisian Arabic' },
  { key: 83, value: 'Sanaani Spoken Arabic' },
  { key: 84, value: 'Min Bei Chinese' },
  { key: 85, value: 'Southern Pashto' },
  { key: 86, value: 'Rundi' },
  { key: 87, value: 'Czech' },
  { key: 88, value: 'Taʽizzi-Adeni Arabic' },
  { key: 89, value: 'Uyghur' },
  { key: 90, value: 'Min Dong Chinese' },
  { key: 91, value: 'Sylheti' },
];
