export const Nationality = [
  { key: 1, value: 'Afghanistan' },
  { key: 2, value: 'Albania' },
  { key: 3, value: 'American Samoa' },
  { key: 4, value: 'Andorra' },
  { key: 5, value: 'Angola' },
  { key: 6, value: 'Anguilla' },
  { key: 7, value: 'Antarctica' },
  { key: 8, value: 'Antigua and Barbuda' },
  { key: 9, value: 'Argentina' },
  { key: 10, value: 'Armenia' },
  { key: 11, value: 'Aruba' },
  { key: 12, value: 'Australia' },
  { key: 13, value: 'Austria' },
  { key: 14, value: 'Azerbaijan' },

  { key: 15, value: 'Bahamas' },
  { key: 16, value: 'Bahrain' },
  { key: 17, value: 'Bangladesh' },
  { key: 18, value: 'Barbados' },
  { key: 19, value: 'Belarus' },
  { key: 20, value: 'Belgium' },
  { key: 21, value: 'Belize' },
  { key: 22, value: 'Benin' },
  { key: 23, value: 'Bermuda' },
  { key: 24, value: 'Bhutan' },
  { key: 25, value: 'Bolivia' },
  { key: 26, value: 'Bosnia and Herzegovina' },
  { key: 27, value: 'Botswana' },
  { key: 28, value: 'Brazil' },
  { key: 29, value: 'Brunei Darussalam' },
  { key: 30, value: 'Bulgaria' },
  { key: 31, value: 'Burkina Faso' },
  { key: 32, value: 'Burundi' },

  { key: 33, value: 'Cambodia' },
  { key: 34, value: 'Cameroon' },
  { key: 35, value: 'Canada' },
  { key: 36, value: 'Cape Verde' },
  { key: 37, value: 'Cayman Islands' },
  { key: 38, value: 'Central African Republic' },
  { key: 39, value: 'Chad' },
  { key: 40, value: 'Chile' },
  { key: 41, value: 'China' },
  { key: 42, value: 'Christmas Island' },
  { key: 43, value: 'Cocos (Keeling) Islands' },
  { key: 44, value: 'Colombia' },
  { key: 45, value: 'Comoros' },
  { key: 46, value: 'Cook Islands' },
  { key: 47, value: 'Costa Rica' },
  { key: 48, value: 'Croatia' },
  { key: 49, value: 'Cuba' },
  { key: 50, value: 'Cyprus' },
  { key: 51, value: 'Czech Republic' },

  { key: 52, value: 'Denmark' },
  { key: 53, value: 'Djibouti' },
  { key: 54, value: 'Dominica' },
  { key: 55, value: 'Dominican Republic' },

  { key: 56, value: 'East Timor' },
  { key: 57, value: 'Ecuador' },
  { key: 58, value: 'Egypt' },
  { key: 59, value: 'El Salvador' },
  { key: 60, value: 'Equatorial Guinea' },
  { key: 61, value: 'Eritrea' },
  { key: 62, value: 'Estonia' },
  { key: 63, value: 'Ethiopia' },

  { key: 64, value: 'Falkland Islands' },
  { key: 65, value: 'Faroe Islands' },
  { key: 66, value: 'Fiji' },
  { key: 67, value: 'Finland' },
  { key: 68, value: 'France' },
  { key: 69, value: 'French Guiana' },
  { key: 70, value: 'French Polynesia' },
  { key: 71, value: 'French Southern Territories' },

  { key: 72, value: 'Gabon' },
  { key: 74, value: 'Georgia' },
  { key: 74, value: 'Germany' },
  { key: 75, value: 'Ghana' },
  { key: 76, value: 'Gibraltar' },
  { key: 77, value: 'Greece' },
  { key: 78, value: 'Greenland' },
  { key: 79, value: 'Grenada' },
  { key: 80, value: 'Guadeloupe' },
  { key: 81, value: 'Guam' },
  { key: 82, value: 'Guatemala' },
  { key: 83, value: 'Guinea' },
  { key: 84, value: 'Guinea-Bissau' },
  { key: 85, value: 'Guyana' },

  { key: 86, value: 'Haiti' },
  { key: 87, value: 'Holy See' },
  { key: 88, value: 'Honduras' },
  { key: 89, value: 'Hong Kong' },
  { key: 90, value: 'Hungary' },

  { key: 91, value: 'Iceland' },
  { key: 92, value: 'India' },
  { key: 93, value: 'Indonesia' },
  { key: 94, value: 'Iran' },
  { key: 95, value: 'Iraq' },
  { key: 96, value: 'Ireland' },
  { key: 97, value: 'Israel' },
  { key: 98, value: 'Italy' },
  { key: 99, value: 'Ivory Coast' },

  { key: 100, value: 'Jamaica' },
  { key: 101, value: 'Japan' },
  { key: 102, value: 'Jordan' },

  { key: 103, value: 'Kazakhstan' },
  { key: 104, value: 'Kenya' },
  { key: 105, value: 'Kiribati' },
  { key: 106, value: 'North Korea' },
  { key: 107, value: 'South Korea' },
  { key: 108, value: 'Kosovo' },
  { key: 109, value: 'Kuwait' },
  { key: 110, value: 'Kyrgyzstan' },

  { key: 111, value: 'Lao' },
  { key: 112, value: 'Latvia' },
  { key: 113, value: 'Lebanon' },
  { key: 114, value: 'Lesotho' },
  { key: 115, value: 'Liberia' },
  { key: 116, value: 'Libya' },
  { key: 117, value: 'Liechtenstein' },
  { key: 118, value: 'Lithuania' },
  { key: 119, value: 'Luxembourg' },

  { key: 120, value: 'Macau' },
  { key: 121, value: 'Madagascar' },
  { key: 122, value: 'Malawi' },
  { key: 123, value: 'Malaysia' },
  { key: 124, value: 'Maldives' },
  { key: 125, value: 'Mali' },
  { key: 126, value: 'Malta' },
  { key: 127, value: 'Marshall Islands' },
  { key: 128, value: 'Martinique' },
  { key: 129, value: 'Mauritania' },
  { key: 130, value: 'Mauritius' },
  { key: 131, value: 'Mayotte' },
  { key: 132, value: 'Mexico' },
  { key: 133, value: 'Micronesia' },
  { key: 134, value: 'Moldova' },
  { key: 135, value: 'Monaco' },
  { key: 136, value: 'Mongolia' },
  { key: 137, value: 'Montenegro' },
  { key: 138, value: 'Montserrat' },
  { key: 139, value: 'Morocco' },
  { key: 140, value: 'Mozambique' },
  { key: 141, value: 'Myanmar' },

  { key: 142, value: 'Namibia' },
  { key: 143, value: 'Nauru' },
  { key: 144, value: 'Nepal' },
  { key: 145, value: 'Netherlands' },
  { key: 146, value: 'Netherlands Antilles' },
  { key: 147, value: 'New Caledonia' },
  { key: 148, value: 'New Zealand' },
  { key: 149, value: 'Nicaragua' },
  { key: 150, value: 'Niger' },
  { key: 151, value: 'Nigeria' },
  { key: 152, value: 'Niue' },
  { key: 153, value: 'North Macedonia' },
  { key: 154, value: 'Northern Mariana Islands' },
  { key: 155, value: 'Norway' },

  { key: 156, value: 'Oman' },

  { key: 157, value: 'Pakistan' },
  { key: 158, value: 'Palau' },
  { key: 159, value: 'Palestinian territories' },
  { key: 160, value: 'Panama' },
  { key: 161, value: 'Papua New Guinea' },
  { key: 162, value: 'Paraguay' },
  { key: 163, value: 'Peru' },
  { key: 164, value: 'Philippines' },
  { key: 165, value: 'Pitcairn Island' },
  { key: 166, value: 'Poland' },
  { key: 167, value: 'Portugal' },
  { key: 168, value: 'Puerto Rico' },

  { key: 169, value: 'Qatar' },

  { key: 170, value: 'Reunion Island' },
  { key: 171, value: 'Romania' },
  { key: 172, value: 'Russian Federation' },
  { key: 173, value: 'Rwanda' },

  { key: 174, value: 'Saint Kitts and Nevis' },
  { key: 175, value: 'Saint Lucia' },
  { key: 176, value: 'Saint Vincent and the Grenadines' },
  { key: 177, value: 'Samoa' },
  { key: 178, value: 'San Marino' },
  { key: 179, value: 'Sao Tome and Principe' },
  { key: 180, value: 'Saudi Arabia' },
  { key: 181, value: 'Senegal' },
  { key: 182, value: 'Serbia' },
  { key: 183, value: 'Seychelles' },
  { key: 184, value: 'Sierra Leone' },
  { key: 185, value: 'Singapore' },
  { key: 186, value: 'Slovakia' },
  { key: 187, value: 'Slovenia' },
  { key: 188, value: 'Solomon Islands' },
  { key: 189, value: 'Somalia' },
  { key: 190, value: 'South Africa' },
  { key: 191, value: 'South Sudan' },
  { key: 192, value: 'Spain' },
  { key: 193, value: 'Sri Lanka' },
  { key: 194, value: 'Sudan' },
  { key: 195, value: 'Suriname' },
  { key: 196, value: 'Swaziland' },
  { key: 197, value: 'Sweden' },
  { key: 198, value: 'Switzerland' },
  { key: 199, value: 'Syria' },

  { key: 200, value: 'Taiwan' },
  { key: 201, value: 'Tajikistan' },
  { key: 202, value: 'Tanzania' },
  { key: 203, value: 'Thailand' },
  { key: 204, value: 'Tibet' },
  { key: 205, value: 'Timor-Leste' },
  { key: 206, value: 'Togo' },
  { key: 207, value: 'Tokelau' },
  { key: 208, value: 'Tonga' },
  { key: 209, value: 'Trinidad and Tobago' },
  { key: 210, value: 'Tunisia' },
  { key: 211, value: 'Turkey' },
  { key: 212, value: 'Turkmenistan' },
  { key: 213, value: 'Turks and Caicos Islands' },
  { key: 214, value: 'Tuvalu' },

  { key: 215, value: 'Uganda' },
  { key: 216, value: 'Ukraine' },
  { key: 217, value: 'United Arab Emirates' },
  { key: 218, value: 'United Kingdom' },
  { key: 219, value: 'United States' },
  { key: 220, value: 'Uruguay' },
  { key: 221, value: 'Uzbekistan' },

  { key: 222, value: 'Vanuatu' },
  { key: 223, value: 'Vatican City State' },
  { key: 224, value: 'Venezuela' },
  { key: 225, value: 'Vietnam' },
  { key: 226, value: 'Virgin Islands' },

  { key: 227, value: 'Wallis and Futuna Islands' },
  { key: 228, value: 'Western Sahara' },

  { key: 228, value: 'Yemen' },

  { key: 229, value: 'Zambia' },
  { key: 230, value: 'Zimbabwe' },
];
