export const POARoles = {
  ADMIN:'SKILSHEET_ADMIN',
  PIC:'SKILLSHEET_PIC',
  CANDIDATE : 'SKILSHEET_CANDIDATE',
  SALE : 'SKILSHEET_SALE',
  RECRUITER : 'SKILSHEET_RECRUITER',
  STAFF : 'SKILSHEET_STAFF'
}